In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dados_1sem = 'Preços semestrais - AUTOMOTIVOS_2025.01.csv'
df_1sem = pd.read_csv(dados_1sem, sep=';')
df_1sem.head(3)

C:\Users\rafael.armando\AppData\Local\Temp\ipykernel_96872\3132973569.py:2: DtypeWarning: Columns (0: Regiao - Sigla, 1: Estado - Sigla, 2: Municipio, 3: Revenda, 4: CNPJ da Revenda, 5: Nome da Rua, 6: Numero Rua, 7: Complemento, 8: Bairro, 9: Cep, 10: Produto, 11: Data da Coleta, 12: Valor de Venda, 13: Unidade de Medida, 14: Bandeira) have mixed types. Specify dtype option on import or set low_memory=False.
  df_1sem = pd.read_csv(dados_1sem, sep=';')

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN

In [ ]:
dados_2sem = 'Preços semestrais - AUTOMOTIVOS_2025.02.csv'
df_2sem = pd.read_csv(dados_2sem, sep=';')
df_2sem.head(3)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,AL,DELMIRO GOUVEIA,COMERCIO DE COMBUSTIVEIS NENZITA LTDA,4431113000100,AVENIDA CAXANGA,126,NaN,PEDRA VELHA,57480-000,DIESEL,01/07/2025,"6,69",NaN,R$ / litro,BRANCA
1,N,AP,MACAPA,SEPE TIARAJU EMPREENDIMENTOS LTDA,5297501000286,RUA SETENTRIONAL,S/N,ESQUINA COM BEIRA RIO,ARAXÁ,68903-640,DIESEL,01/07/2025,"6,33",NaN,R$ / litro,BRANCA
2,NE,BA,IPIRA,AUTO POSTO AUGUSTU'S LTDA,2448248000145,SITIO SAO JOSE,SN,NaN,SEDE,44600-000,DIESEL,01/07/2025,"6,9",NaN,R$ / litro,ALE

In [ ]:
df_anp = pd.concat([df_1sem, df_2sem], ignore_index= True)

In [ ]:
df_anp

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA,01/01/2025,"6,29",NaN,R$ / litro,RAIZEN
1,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,GASOLINA ADITIVADA,01/01/2025,"6,49",NaN,R$ / litro,RAIZEN
2,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,DIESEL S10,01/01/2025,"6,19",NaN,R$ / litro,RAIZEN
3,NE,CE,SOBRAL,ECONOGÁS DO BRASIL DIST. DERIV. DE PET. BIOC. ...,08.775.979/0002-62,RUA TABELIÃO IDELFONSO CAVALCANTI,455,NaN,CENTRO,62010-000,ETANOL,01/01/2025,"5,19",NaN,R$ / litro,RAIZEN
4,NE,CE,SOBRAL,V.C.EMPREENDIMENTOS LTDA,03.551.935/0002-35,AVENIDA JOSE EUCLIDES FERREIRA GOMES,30,POSTO FLASH,CORACAO DE JESUS,62043-070,GASOLINA,01/01/2025,"6,53",NaN,R$ / litro,RAIZEN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
813726,NE,BA,ALAGOINHAS,2 A COMERCIO DE COMBUSTIVEIS GNV E LUBRIFICANT...,14238511000150,RODOVIA BR 101 KM 116,S/N,SALA 01,CENTRO,48005-440,GNV,31/12/2025,"4,38",NaN,R$ / m3,LARCO
813727,NE,PB,BAYEUX,PETROGAS COMERCIO DE COMBUSTIVEIS LTDA,21553439000111,AVENIDA LIBERDADE,3545,ANDAR: 1; ANEXO: A;,SESI,58306-000,GNV,31/12/2025,"4,85",NaN,R$ / m3,ALE
813728,NE,BA,ILHEUS,BATISTA COMERCIO DE COMBUSTIVEIS E LUBRIFICANT...,28562491000183,AVENIDA FERROVIARIA,S/N,KM 05 RODOVIA ILHEUS,IGUAPE,45658-340,GNV,31/12/2025,"4,73",NaN,R$ / m3,BRANCA
813729,SE,SP,JACAREI,AUTO POSTO BRANCO DE CASTELO LTDA,68912864000385,AVENIDA SIQUEIRA CAMPOS,641,NaN,CENTRO,12308-190,GNV,31/12/2025,"3,99",NaN,R$ / m3,VIBRA
813730,S,RS,LAJEADO,SIM REDE DE POSTOS LTDA,7473735018714,RODOVIA ERS-130,2285,KM 72.8,SANTO ANDRE,95912-000,GNV,31/12/2025,"5,65",NaN,R$ / m3,CHARRUA

In [ ]:
df_anp['Valor de Venda'] = df_anp['Valor de Venda'].str.replace(',', '.').astype(float)

In [ ]:
df_gasolina = df_anp.loc[df_anp['Produto'] == 'GASOLINA']
df_etanol = df_anp.loc[df_anp['Produto'] == 'ETANOL']

In [ ]:
df_media_est_gaso = df_gasolina.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()
df_media_est_gaso

   Estado - Sigla  Valor de Venda
0              AC        7.671043
1              AL        6.331550
2              AM        7.226496
3              AP        6.041904
4              BA        6.390745
5              CE        6.373081
6              DF        6.442591
7              ES        6.256656
8              GO        6.291102
9              MA        6.128841
10             MG        6.130570
11             MS        6.206580
12             MT        6.260951
13             PA        6.401182
14             PB        6.059165
15             PE        6.330366
16             PI        5.925385
17             PR        6.427747
18             RJ        6.145133
19             RN        6.330973
20             RO        6.914577
21             RR        6.947907
22             RS        6.222312
23             SC        6.393332
24             SE        6.547728
25             SP        6.091283
26             TO        6.534131

In [ ]:
df_media_est_gaso = df_media_est_gaso.sort_values(by='Valor de Venda', ascending=False)
df_media_est_gaso

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728
26             TO        6.534131
6              DF        6.442591
17             PR        6.427747
13             PA        6.401182
23             SC        6.393332
4              BA        6.390745
5              CE        6.373081
1              AL        6.331550
19             RN        6.330973
15             PE        6.330366
8              GO        6.291102
12             MT        6.260951
7              ES        6.256656
22             RS        6.222312
11             MS        6.206580
18             RJ        6.145133
10             MG        6.130570
9              MA        6.128841
25             SP        6.091283
14             PB        6.059165
3              AP        6.041904
16             PI        5.925385

In [ ]:
df_media_est_etanol = df_etanol.groupby('Estado - Sigla')['Valor de Venda'].mean().reset_index()
df_media_est_etanol

# o objetivo é comparar os preços médios de etanol por estado, para isso, vamos juntar os dois dataframes usando a coluna 'Estado - Sigla' como chave

   Estado - Sigla  Valor de Venda
0              AC        5.450321
1              AL        4.974708
2              AM        5.429408
3              AP        5.428462
4              BA        4.787785
5              CE        5.115794
6              DF        4.641591
7              ES        4.527789
8              GO        4.453903
9              MA        4.944062
10             MG        4.333693
11             MS        4.078334
12             MT        4.160479
13             PA        4.840288
14             PB        4.491290
15             PE        4.772174
16             PI        4.625402
17             PR        4.457752
18             RJ        4.610375
19             RN        4.999004
20             RO        5.213401
21             RR        5.164806
22             RS        4.873926
23             SC        4.741009
24             SE        4.853322
25             SP        4.104169
26             TO        4.773923

In [ ]:
df_media_est_etanol = df_media_est_etanol.sort_values(by='Valor de Venda', ascending=False)
df_media_est_etanol

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806
5              CE        5.115794
19             RN        4.999004
1              AL        4.974708
9              MA        4.944062
22             RS        4.873926
24             SE        4.853322
13             PA        4.840288
4              BA        4.787785
26             TO        4.773923
15             PE        4.772174
23             SC        4.741009
6              DF        4.641591
16             PI        4.625402
18             RJ        4.610375
7              ES        4.527789
14             PB        4.491290
17             PR        4.457752
8              GO        4.453903
10             MG        4.333693
12             MT        4.160479
25             SP        4.104169
11             MS        4.078334

In [ ]:
df_media_est_gaso.head(5)

   Estado - Sigla  Valor de Venda
0              AC        7.671043
2              AM        7.226496
21             RR        6.947907
20             RO        6.914577
24             SE        6.547728

In [ ]:
df_media_est_etanol.head(5)

   Estado - Sigla  Valor de Venda
0              AC        5.450321
2              AM        5.429408
3              AP        5.428462
20             RO        5.213401
21             RR        5.164806

In [ ]:
df_media_regiao_gaso = df_gasolina.groupby('Regiao - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_gaso

  Regiao - Sigla  Valor de Venda
0             CO        6.293839
1              N        6.716720
2             NE        6.288195
3              S        6.331845
4             SE        6.115093

In [ ]:
df_media_regiao_gaso = df_media_regiao_gaso.sort_values(by='Valor de Venda', ascending=False)
df_media_regiao_gaso

  Regiao - Sigla  Valor de Venda
1              N        6.716720
3              S        6.331845
0             CO        6.293839
2             NE        6.288195
4             SE        6.115093

In [ ]:
df_media_regiao_etanol = df_etanol.groupby('Regiao - Sigla')['Valor de Venda'].mean().reset_index()
df_media_regiao_etanol

  Regiao - Sigla  Valor de Venda
0             CO        4.352734
1              N        5.085354
2             NE        4.845289
3              S        4.629784
4             SE        4.237751

In [ ]:
df_media_regiao_etanol = df_media_regiao_etanol.sort_values(by='Valor de Venda', ascending=False)
df_media_regiao_etanol

  Regiao - Sigla  Valor de Venda
1              N        5.085354
2             NE        4.845289
3              S        4.629784
0             CO        4.352734
4             SE        4.237751

In [ ]:
df_municipio_gaso = df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_municipio_gaso = df_municipio_gaso.sort_values(by='Valor de Venda', ascending=False)
df_municipio_gaso.head(10)

           Municipio  Valor de Venda
276        PARINTINS        8.313433
120  CRUZEIRO DO SUL        7.992080
316       RIO BRANCO        7.492689
46           BARUERI        7.257318
38              BAGE        7.190867
233           MANAUS        7.069509
125  DELMIRO GOUVEIA        7.059354
332         SANTAREM        7.044586
291    PIMENTA BUENO        7.044259
6           ALENQUER        7.032374

In [ ]:
df_municipio_etanol = df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_municipio_etanol = df_municipio_etanol.sort_values(by='Valor de Venda', ascending=False)
df_municipio_etanol.head(10)

                 Municipio  Valor de Venda
119        CRUZEIRO DO SUL        5.935372
406                VILHENA        5.675648
328  SANTANA DO LIVRAMENTO        5.617932
183              ITAPIPOCA        5.592132
115                CRATEUS        5.477391
232                 MANAUS        5.445055
102                   CODO        5.441439
228                 MACAPA        5.428462
162                    ICO        5.343868
231             MANACAPURU        5.338944

In [ ]:
df_municipio_gaso = df_gasolina.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_municipio_gaso = df_municipio_gaso.sort_values(by='Valor de Venda')
df_municipio_gaso.head(10)

               Municipio  Valor de Venda
348  SAO JOSE DE RIBAMAR        5.677958
353             SAO LUIS        5.709328
148             GOIATUBA        5.737596
377              TAUBATE        5.749248
195              JACAREI        5.762268
13            ANANINDEUA        5.779130
83          CAMPO GRANDE        5.818789
380             TERESINA        5.848389
26            ARARAQUARA        5.853007
253              NITEROI        5.855828

In [ ]:
df_municipio_etanol = df_etanol.groupby('Municipio')['Valor de Venda'].mean().reset_index()
df_municipio_etanol = df_municipio_etanol.sort_values(by='Valor de Venda')
df_municipio_etanol.head(10)

                 Municipio  Valor de Venda
346  SAO JOSE DO RIO PRETO        3.741439
18               ARACATUBA        3.761291
222                   LINS        3.829775
55                 BIRIGUI        3.845749
82            CAMPO GRANDE        3.860465
413            VOTUPORANGA        3.889227
147               GOIATUBA        3.890171
307    PRESIDENTE PRUDENTE        3.897089
235                MARILIA        3.908255
197                  JALES        3.921549

In [ ]:
df_etanol = df_anp.loc[df_anp['Produto'] == 'ETANOL']